// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AttachProcess(arg1:number):Promise<void>;

export function AttachedPID():Promise<number>;

export function ConnectTrainer():Promise<main.TrainerStatus>;

export function DisconnectTrainer():Promise<main.TrainerStatus>;

export function GetModuleBase(arg1:number):Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function GetTrainerStatus():Promise<main.TrainerStatus>;

export function KillApp():Promise<void>;

export function ListProcesses():Promise<Array<main.ProcessInfo>>;

export function ListTrainers():Promise<Array<main.TrainerSummary>>;

export function LoadTrainer(arg1:string):Promise<main.TrainerStatus>;

export function NarrowValue(arg1:number):Promise<main.ScanResult>;

export function NarrowValueFloat(arg1:number):Promise<main.ScanResult>;

export function PickTrainerDir():Promise<string>;

export function ReadAllTypes(arg1:string):Promise<main.AllTypesResult>;

export function ReadValue(arg1:string):Promise<number>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function ScanByMode(arg1:string):Promise<main.ScanResult>;

export function ScanValue(arg1:number):Promise<main.ScanResult>;

export function ScanValueFloat(arg1:number):Promise<main.ScanResult>;

export function SetFullscreen(arg1:boolean):Promise<void>;

export function StopTestFreeze():Promise<void>;

export function TestFreeze(arg1:string,arg2:number):Promise<void>;

export function ToggleCheat(arg1:number,arg2:boolean,arg3:number):Promise<main.TrainerStatus>;

export function TrainerImage(arg1:string):Promise<string>;

export function UserTrainerDir():Promise<string>;

export function WalkPointerChain(arg1:string,arg2:Array<string>):Promise<main.PointerChainResult>;

export function WriteValue(arg1:string,arg2:number):Promise<void>;
