// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachProcess(arg1) {
  return window['go']['main']['App']['AttachProcess'](arg1);
}

export function AttachedPID() {
  return window['go']['main']['App']['AttachedPID']();
}

export function ConnectTrainer() {
  return window['go']['main']['App']['ConnectTrainer']();
}

export function GetTrainerStatus() {
  return window['go']['main']['App']['GetTrainerStatus']();
}

export function ListProcesses() {
  return window['go']['main']['App']['ListProcesses']();
}

export function ListTrainers() {
  return window['go']['main']['App']['ListTrainers']();
}

export function LoadTrainer(arg1) {
  return window['go']['main']['App']['LoadTrainer'](arg1);
}

export function NarrowValue(arg1) {
  return window['go']['main']['App']['NarrowValue'](arg1);
}

export function ReadValue(arg1) {
  return window['go']['main']['App']['ReadValue'](arg1);
}

export function ScanValue(arg1) {
  return window['go']['main']['App']['ScanValue'](arg1);
}

export function ToggleCheat(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleCheat'](arg1, arg2, arg3);
}

export function UserTrainerDir() {
  return window['go']['main']['App']['UserTrainerDir']();
}

export function WriteValue(arg1, arg2) {
  return window['go']['main']['App']['WriteValue'](arg1, arg2);
}
