// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachProcess(arg1) {
  return window['go']['main']['App']['AttachProcess'](arg1);
}

export function AttachedPID() {
  return window['go']['main']['App']['AttachedPID']();
}

export function ConnectTrainer() {
  return window['go']['main']['App']['ConnectTrainer']();
}

export function DisconnectTrainer() {
  return window['go']['main']['App']['DisconnectTrainer']();
}

export function GetModuleBase(arg1) {
  return window['go']['main']['App']['GetModuleBase'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTrainerStatus() {
  return window['go']['main']['App']['GetTrainerStatus']();
}

export function KillApp() {
  return window['go']['main']['App']['KillApp']();
}

export function ListProcesses() {
  return window['go']['main']['App']['ListProcesses']();
}

export function ListTrainers() {
  return window['go']['main']['App']['ListTrainers']();
}

export function LoadTrainer(arg1) {
  return window['go']['main']['App']['LoadTrainer'](arg1);
}

export function NarrowValue(arg1) {
  return window['go']['main']['App']['NarrowValue'](arg1);
}

export function PickTrainerDir() {
  return window['go']['main']['App']['PickTrainerDir']();
}

export function ReadAllTypes(arg1) {
  return window['go']['main']['App']['ReadAllTypes'](arg1);
}

export function ReadValue(arg1) {
  return window['go']['main']['App']['ReadValue'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanByMode(arg1) {
  return window['go']['main']['App']['ScanByMode'](arg1);
}

export function ScanValue(arg1) {
  return window['go']['main']['App']['ScanValue'](arg1);
}

export function StopTestFreeze() {
  return window['go']['main']['App']['StopTestFreeze']();
}

export function TestFreeze(arg1, arg2) {
  return window['go']['main']['App']['TestFreeze'](arg1, arg2);
}

export function ToggleCheat(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleCheat'](arg1, arg2, arg3);
}

export function TrainerImage(arg1) {
  return window['go']['main']['App']['TrainerImage'](arg1);
}

export function UserTrainerDir() {
  return window['go']['main']['App']['UserTrainerDir']();
}

export function WriteValue(arg1, arg2) {
  return window['go']['main']['App']['WriteValue'](arg1, arg2);
}
