// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AttachProcess(arg1:number):Promise<void>;

export function AttachedPID():Promise<number>;

export function ConnectTrainer():Promise<main.TrainerStatus>;

export function GetTrainerStatus():Promise<main.TrainerStatus>;

export function ListProcesses():Promise<Array<main.ProcessInfo>>;

export function ListTrainers():Promise<Array<main.TrainerSummary>>;

export function LoadTrainer(arg1:string):Promise<main.TrainerStatus>;

export function NarrowValue(arg1:number):Promise<main.ScanResult>;

export function ReadValue(arg1:string):Promise<number>;

export function ScanValue(arg1:number):Promise<main.ScanResult>;

export function ToggleCheat(arg1:number,arg2:boolean,arg3:number):Promise<main.TrainerStatus>;

export function TrainerImage(arg1:string):Promise<string>;

export function UserTrainerDir():Promise<string>;

export function WriteValue(arg1:string,arg2:number):Promise<void>;
